-- =============================================
-- RBAC access control system PostgreSQL script
-- PostgreSQL 12+
-- =============================================

-- Note: Supabase manages the database; do not run CREATE DATABASE/USE.

-- Clean up (drop views first to avoid dependency issues)

DROP TABLE IF EXISTS sys_role_menu CASCADE;
DROP TABLE IF EXISTS sys_user_role CASCADE;
DROP TABLE IF EXISTS sys_menu CASCADE;
DROP TABLE IF EXISTS sys_role CASCADE;
DROP TABLE IF EXISTS sys_user CASCADE;

-- =============================================
-- 1. Users table
-- =============================================
CREATE TABLE sys_user (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    password VARCHAR(128) NOT NULL,
    phone VARCHAR(13) DEFAULT NULL,
    email VARCHAR(36) DEFAULT NULL,
    sex VARCHAR(2) DEFAULT '0',
    is_admin BOOLEAN DEFAULT FALSE,
    is_account_non_expired BOOLEAN DEFAULT TRUE,
    is_account_non_locked BOOLEAN DEFAULT TRUE,
    is_credentials_non_expired BOOLEAN DEFAULT TRUE,
    is_enabled BOOLEAN DEFAULT TRUE,
    nick_name VARCHAR(36) DEFAULT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE sys_user ADD CONSTRAINT uk_username UNIQUE (username);
CREATE INDEX idx_phone ON sys_user (phone);
CREATE INDEX idx_email ON sys_user (email);
CREATE INDEX idx_create_time_user ON sys_user (create_time);

-- =============================================
-- 2. Roles table
-- =============================================
CREATE TABLE sys_role (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(64) NOT NULL,
    type VARCHAR(10) DEFAULT NULL,
    remark VARCHAR(128) DEFAULT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE sys_role ADD CONSTRAINT uk_role_name UNIQUE (role_name);
CREATE INDEX idx_create_time_role ON sys_role (create_time);

-- =============================================
-- 3. Menus table
-- =============================================
CREATE TABLE sys_menu (
    menu_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT DEFAULT 0,
    title VARCHAR(64) NOT NULL,
    code VARCHAR(64) DEFAULT NULL,
    name VARCHAR(36) DEFAULT NULL,
    path VARCHAR(36) DEFAULT NULL,
    url VARCHAR(128) DEFAULT NULL,
    type VARCHAR(2) NOT NULL DEFAULT '1',
    icon VARCHAR(36) DEFAULT NULL,
    parent_name VARCHAR(64) DEFAULT NULL,
    order_num INTEGER DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_parent_id ON sys_menu (parent_id);
CREATE INDEX idx_order_num ON sys_menu (order_num);

-- =============================================
-- 4. User-role relation table
-- =============================================
CREATE TABLE sys_user_role (
    user_role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    CONSTRAINT uk_user_role UNIQUE (user_id, role_id)
);

CREATE INDEX idx_user_id ON sys_user_role (user_id);
CREATE INDEX idx_role_id ON sys_user_role (role_id);

-- =============================================
-- 5. Role-menu relation table
-- =============================================
CREATE TABLE sys_role_menu (
    role_menu_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL,
    CONSTRAINT uk_role_menu UNIQUE (role_id, menu_id)
);

CREATE INDEX idx_role_id_rm ON sys_role_menu (role_id);
CREATE INDEX idx_menu_id_rm ON sys_role_menu (menu_id);

